[book]
title = "Ruru"
authors = ["mathcomics"]
language = "en"
src = "src"

[output.html]
site-url = "/ruru/"
git-repository-url = "https://github.com/mathcomics/ruru"
edit-url-template = "https://github.com/mathcomics/ruru/edit/main/{path}"
additional-css = ["theme/custom.css"]
default-theme = "light"
